apiVersion: v1
kind: Pod
metadata: 
  name: todoapp-pod
spec:
  containers:
  - name: nestjs
    image: todoapp:0.0.4
    ports: 
    - containerPort: 3000
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_DATABASE
      value: "todoapp"
    ports:
    - containerPort: 3306

